// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvcyyamrzwbuqhxqffpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2Y3l5YW1yendidXFoeHFmZnB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NzY0MTcsImV4cCI6MjA3MDM1MjQxN30.nsuje9s_PLyGTo_JYQqQYi4QeORLA00X7eFd1SFPuP0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});